# Change baseurl before deploy
baseURL = "https://yingnobody.github.io/chashmal/"
languageCode = "en-us"
title = "C   H   A   S   H   M   A   L"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using - disqus = add comments
# disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5

[params]
favicon = "static/favicon.png"
